# Generated by Terraform — do not edit manually
# K8s Secrets (catalog-db, orders-db, orders-rabbitmq) are pre-created by Terraform

catalog:
  fullnameOverride: catalog
  app:
    persistence:
      provider: mysql
      endpoint: "${catalog_endpoint}"
      database: catalog
      secret:
        create: false
        name: catalog-db
        usernameKey: RETAIL_CATALOG_PERSISTENCE_USER
        passwordKey: RETAIL_CATALOG_PERSISTENCE_PASSWORD
  mysql:
    create: false

cart:
  fullnameOverride: carts
  serviceAccount:
    create: true
    name: carts
    annotations:
      eks.amazonaws.com/role-arn: "${cart_irsa_role_arn}"
  app:
    persistence:
      provider: dynamodb
      dynamodb:
        tableName: "${dynamodb_table_name}"
        createTable: false
        region: "${region}"
  dynamodb:
    create: false

checkout:
  fullnameOverride: checkout
  app:
    persistence:
      provider: redis
    endpoints:
      orders: http://orders:80
  redis:
    create: true
    fullnameOverride: redis

orders:
  fullnameOverride: orders
  app:
    persistence:
      provider: postgres
      endpoint: "${orders_endpoint}"
      database: orders
      secret:
        create: false
        name: orders-db
        usernameKey: RETAIL_ORDERS_PERSISTENCE_USER
        passwordKey: RETAIL_ORDERS_PERSISTENCE_PASSWORD
    messaging:
      provider: rabbitmq
      rabbitmq:
        host: rabbitmq
        port: 5672
        secret:
          create: false
          name: orders-rabbitmq
          usernameKey: RETAIL_ORDERS_MESSAGING_RABBITMQ_USERNAME
          passwordKey: RETAIL_ORDERS_MESSAGING_RABBITMQ_PASSWORD
  postgresql:
    create: false
  rabbitmq:
    create: true
    fullnameOverride: rabbitmq

ui:
  fullnameOverride: ui
  service:
    type: ClusterIP
    port: 80
  ingress:
    enabled: true
    className: alb
    annotations:
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/target-type: ip
      alb.ingress.kubernetes.io/healthcheck-path: /actuator/health/liveness
      alb.ingress.kubernetes.io/tags: "Project=karatu-2025-capstone"
%{ if domain_name != "" && acm_certificate_arn != "" ~}
      alb.ingress.kubernetes.io/certificate-arn: "${acm_certificate_arn}"
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
      alb.ingress.kubernetes.io/ssl-redirect: "443"
%{ endif ~}
    hosts:
      - host: "${domain_name}"
        paths:
          - path: /
            pathType: Prefix
    tls: []
